[package]
name = "rustseq_mini"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
num_cpus = "1.16"

# CUDA dependencies for RTX 4070
cuda = "0.3"
cuda-sys = "0.2"
cuda-driver-sys = "0.3"

[build-dependencies]
cc = "1.0"