[package]
name = "simd_kmer_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
needletail = "0.4"
rayon = "1.5"
dashmap = "5.0"
fxhash = "0.2"
clap = { version = "4.0", features = ["derive"] }
